#!/bin/bash 
python -m coconet.main ../cut/Trimmed_RF02977.fa 
python -m coconet.main ../cut/Trimmed_RF00028.fa 
python -m coconet.main ../cut/Trimmed_RF00168.fa 
python -m coconet.main ../cut/Trimmed_RF00059.fa 
python -m coconet.main ../cut/Trimmed_RF00522.fa 
python -m coconet.main ../cut/Trimmed_RF01079.fa 
python -m coconet.main ../cut/Trimmed_RF01684.fa 
python -m coconet.main ../cut/Trimmed_RF00174.fa 
python -m coconet.main ../cut/Trimmed_RF00386.fa 
python -m coconet.main ../cut/Trimmed_RF00163.fa 
python -m coconet.main ../cut/Trimmed_RF01750.fa 
python -m coconet.main ../cut/Trimmed_RF03493.fa 
python -m coconet.main ../cut/Trimmed_RF03300.fa 
python -m coconet.main ../cut/Trimmed_RF01136.fa 
python -m coconet.main ../cut/Trimmed_RF00419.fa 
python -m coconet.main ../cut/Trimmed_RF00250.fa 
python -m coconet.main ../cut/Trimmed_RF03072.fa 
python -m coconet.main ../cut/Trimmed_RF03013.fa 
python -m coconet.main ../cut/Trimmed_RF00167.fa 
python -m coconet.main ../cut/Trimmed_RF00176.fa 
python -m coconet.main ../cut/Trimmed_RF02933.fa 
